spring:
  data:
    mongodb:
      uri: mongodb+srv://ankitrockde783:Pass%40201003@cluster1.b6cry.mongodb.net/online_banking_db?retryWrites=true&w=majority&appName=Cluster1
      database: online_banking_db

  devtools:
    restart:
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ankytofficial1@gmail.com
    password: fojo shnz rgig svca
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

server:
  port: 8080

jwt:
  secret: uzl4KZyU4pY5TWtaGlzhUcJPKVQ1tS0kfItejc0UAzYKN4P1X65exKO/Vjd/E+Wfh/rJDBJOXhlfjoYhxBdC+g==

frontend:
  url: http://localhost:5173


ratelimit:
  enabled: true
  requests: 5
  duration: 60  # in seconds (i.e., 5 requests per 60 seconds)

logging:
  file:
    name: logs/online-banking-app.log  # Relative path (will be created inside your project root)
  pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.bankingsystem.security.RateLimitingFilter: DEBUG
    com.bankingsystem.controller.TransactionController: DEBUG
    com.bankingsystem.service.TransactionService: DEBUG
    com.bankingsystem.controller.AdminController: DEBUG
    com.bankingsystem.service.MailService: INFO
    com.bankingsystem.service.CustomUserDetailsService: DEBUG

